
server.port=8088

spring.report-datasource.jdbcUrl=jdbc:postgresql://localhost:5432/report-migration-bk
spring.report-datasource.username=postgres
spring.report-datasource.password=root
spring.report-jpa.hibernate.ddl-auto=none
spring.report-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mariadb-datasource.jdbcUrl=jdbc:mariadb://192.168.130.101:3306/autounderwriting_life
spring.mariadb-datasource.username=ausyslive
spring.mariadb-datasource.password=A0100$23
spring.mariadb-jpa.hibernate.ddl-auto=none


spring.softlogic-datasource.jdbcUrl=jdbc:sqlserver://localhost:1434;databaseName=SoftlogicDB;integratedSecurity=true;trustServerCertificate=true
spring.softlogic-datasource.username=
spring.softlogic-datasource.password=
spring.softlogic-jpa.hibernate.ddl-auto=none
spring.softlogic-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.softlogic-jpa.database-platform=org.hibernate.dialect.SQLServerDialect
logging.level.com.microsoft.sqlserver.jdbc=OFF

base.file.source.location=D:/IMS-Reports-AAA
paidClaimReport.file=${base.file.source.location}/claims_reports/PaidClaimsOFLife.xlsm
rejectedClaimReport.file=${base.file.source.location}/claims_reports/RejectedClaimRiders.xls
oustandingClaimReport.file=${base.file.source.location}/claims_reports/OSCLAIMSOFLIFE.xls
declaredClaimReport.file=${base.file.source.location}/claims_reports/DeclaredCLAIMSOFlIFE.xls
closedClaimReport.file=${base.file.source.location}/claims_reports/ClosedClmRep.xls

mainDataReport.file=D:main-data/main Data.xlsx/
mainDataAlhReport.file=D:/main-data/ALH Data.xlsm
cashFlowReport.file=D:/cash_flow_reports/
payMeReport.file=
posSignatureReport.file=

acp.data.file=${base.file.source.location}/ACP Data.xlsm
policy.list.file=${base.file.source.location}/monthEndReports/PolList.xlsm
contact.detail.file=${base.file.source.location}/ContactDetRep-L.xlsm

policy.number.list.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\policy_number_list\\policy_numbers.xlsx
premiumDetailsReport.file=D:/premium details reports/
