spring.application.name=data-migration-adapter

spring.profiles.active=dev3

# Max size allowed for a single file
spring.servlet.multipart.max-file-size=100MB
# Max size allowed for the entire multipart/form-data request
spring.servlet.multipart.max-request-size=100MB
policy.no.sheet=NISHADI-24-4
filter.by.status=0