spring.report-datasource.url=jdbc:postgresql://192.168.130.102:5432/report-migration
spring.report-datasource.username=migration_user
spring.report-datasource.password=100100@AzIT
spring.report-jpa.hibernate.ddl-auto=none
spring.report-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.payme-datasource.url=jdbc:postgresql://192.168.130.102:5432/payment_matching
spring.payme-datasource.username=migration_user
spring.payme-datasource.password=100100@AzIT
spring.payme-jpa.hibernate.ddl-auto=none
spring.payme-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
