server.port=8021

spring.report-datasource.jdbcUrl=jdbc:postgresql://192.168.130.102:5432/report-migration
#spring.report-datasource.username=migration_user
#spring.report-datasource.password=100100@AzIT
spring.report-datasource.username=postgres
spring.report-datasource.password=root
spring.report-jpa.hibernate.ddl-auto=none
spring.report-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mariadb-datasource.jdbcUrl=jdbc:mariadb://192.168.130.101:3306/autounderwriting_life
spring.mariadb-datasource.username=ausyslive
spring.mariadb-datasource.password=A0100$23
spring.mariadb-jpa.hibernate.ddl-auto=none

spring.softlogic-datasource.jdbcUrl=jdbc:sqlserver://SM830375\\SQLEXPRESS;databaseName=SoftlogicDB;trustServerCertificate=true;
spring.softlogic-datasource.username=sa
spring.softlogic-datasource.password=500500@AzIT
spring.softlogic-jpa.hibernate.ddl-auto=none
spring.softlogic-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.softlogic-jpa.database-platform=org.hibernate.dialect.SQLServerDialect
logging.level.com.microsoft.sqlserver.jdbc=OFF

base.file.source.location=D:/IMS-Reports-AAA

paidClaimReport.file=${base.file.source.location}/claims_reports/PaidClaimsOFLife.xlsm
mainDataReport.file=D:main-data/main Data.xlsx/
mainDataAlhReport.file=D:/main-data/ALH Data.xlsm
cashFlowReport.file=D:/Cash Flow
payMeReport.file=
posSignatureReport.file=
contact.detail.file=
acp.data.file=C:/Users/janith.thiwanka/Desktop/Data Migration/ACP Data.xlsm
policy.list.file=C:/Users/janith.thiwanka/Desktop/Data Migration/PolList-2025.xlsm
