server.port=8088

spring.report-datasource.jdbcUrl=jdbc:postgresql://192.168.130.102:5432/report-migration-prod-march
spring.report-datasource.username=postgres
spring.report-datasource.password=root
spring.report-jpa.hibernate.ddl-auto=none
spring.report-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.softlogic-datasource.jdbcUrl=jdbc:sqlserver://192.168.130.103:1433;databaseName=SoftlogicDB;trustServerCertificate=true
spring.softlogic-datasource.username=migration_user
spring.softlogic-datasource.password=MigrU$er@123
spring.softlogic-jpa.hibernate.ddl-auto=none
spring.softlogic-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.softlogic-jpa.database-platform=org.hibernate.dialect.SQLServerDialect
logging.level.com.microsoft.sqlserver.jdbc=OFF

#base.file.source.location=E:\\2026_Data_Migration\\claims_reports\\
base.file.source.location=D:\\IMS-Reports-AAA\\claims_reports\\
paidClaimReport.file=${base.file.source.location}PaidClaimsOFLife.xlsm
rejectedClaimReport.file=${base.file.source.location}RejectedClaimRiders.xls
oustandingClaimReport.file=${base.file.source.location}OSCLAIMSOFLIFE.xls
declaredClaimReport.file=${base.file.source.location}DeclaredCLAIMSOFlIFE.xlsm
closedClaimReport.file=${base.file.source.location}ClosedClmRep.xls

mainDataReport.file=E:\\2026_Data_Migration\\main_data_report\\Main_Data.xlsx
mainDataAlhReport.file=E:\\2026_Data_Migration\\main_data_report\\Main_Data_ALH.xlsx
mainDataAcpReport.file=E:\\2026_Data_Migration\\main_data_report\\Main_Data_ACP.xlsx

cashFlowReport.file=E:\\2026_Data_Migration\\cash_flow_reports\\
payMeReport.file=E:\\2026_Data_Migration\\contact_detail_report\\ContactDetRep-L.xlsm
posSignatureReport.file=
premiumDetailsReport.file=E:\\2026_Data_Migration\\premium_file\\Upload

policy.list.file=${base.file.source.location}/monthEndReports/PolList.xlsm
contact.detail.file=E:\\2026_Data_Migration\\contact_detail_report\\ContactDetRep-L.xlsm
#policyFund.file=E:\\2026_Data_Migration\\unit_link\\ULDataReq.xls
policyFund.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\March-2026-reports\\unit_link\\ULDataReq.xlsm

policy.number.list.file=E:\\2026_Data_Migration\\policy_number_list\\policy_numbers.xlsx