server.port=8088

spring.report-datasource.jdbcUrl=jdbc:postgresql://localhost:5432/report-migration-bk
spring.report-datasource.username=postgres
spring.report-datasource.password=root
spring.report-jpa.hibernate.ddl-auto=none
spring.report-jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.softlogic-datasource.jdbcUrl=jdbc:sqlserver://localhost:1434;databaseName=SoftlogicDB;integratedSecurity=true;trustServerCertificate=true
spring.softlogic-datasource.username=
spring.softlogic-datasource.password=
spring.softlogic-jpa.hibernate.ddl-auto=none
spring.softlogic-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.softlogic-jpa.database-platform=org.hibernate.dialect.SQLServerDialect
logging.level.com.microsoft.sqlserver.jdbc=OFF

base.file.source.location=D:/IMS-Reports-AAA
paidClaimReport.file=${base.file.source.location}/claims_reports/PaidClaimsOFLife.xlsm
rejectedClaimReport.file=${base.file.source.location}/claims_reports/RejectedClaimRiders.xls
oustandingClaimReport.file=${base.file.source.location}/claims_reports/OSCLAIMSOFLIFE.xls
declaredClaimReport.file=${base.file.source.location}/claims_reports/DeclaredCLAIMSOFlIFE.xls
closedClaimReport.file=${base.file.source.location}/claims_reports/ClosedClmRep.xls

mainDataReport.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\main_data_Apr_2026_new_DQ\\Main_Data.xlsx
mainDataAlhReport.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\main_data_Apr_2026_new_DQ\\Main_Data_ALH.xlsx
mainDataAcpReport.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\main_data_Apr_2026_new_DQ\\Main_Data_ACP.xlsx

cashFlowReport.file=D:/cash_flow_reports/
payMeReport.file=D:/ContactDetRep-L.xlsm
posSignatureReport.file=
premiumDetailsReport.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\premium_file\\Upload

policy.list.file=${base.file.source.location}/monthEndReports/PolList.xlsm
contact.detail.file=D:/ContactDetRep-L.xlsm
unitLink.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\April-2026-reports\\unit_link\\ULDataReq.xlsm

policy.number.list.file=C:\\Users\\prabash.dahanayake\\OneDrive - Softlogic Holdings PLC\\2026_Data_Migration\\policy_number_list\\policy_numbers.xlsx
